In [1]:
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

In [3]:
data = randn(3,3)
data

array([[-0.2161,  0.425 , -0.1001],
       [-1.1293, -0.1977,  0.5889],
       [ 0.392 ,  1.1264, -0.674 ]])

In [4]:
data.shape

(3, 3)

In [5]:
data.dtype

dtype('float64')

In [6]:
data2 = [1,2,3,4], [5,6,7,8]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.ndim

2

In [8]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
arr2 = np.array([1,2,3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [15]:
arr2.astype(np.int32)

array([1, 2, 3])

In [17]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[5]

5

In [20]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [21]:
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [22]:
arr_slice[:]=66
arr

array([ 0,  1,  2,  3,  4, 66, 66, 66,  8,  9])

In [23]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [24]:
data = randn(7, 4)
data

array([[ 1.0506,  0.9001, -0.7518,  0.7778],
       [-0.5619,  0.2016, -0.7449, -0.0038],
       [ 1.5603,  0.4021,  0.82  ,  0.6513],
       [ 1.1021,  0.5007,  0.7032, -1.002 ],
       [-0.1882,  0.7621,  0.1871, -0.1801],
       [-0.0625,  0.2762, -0.4286, -0.7441],
       [-2.3445,  0.6991,  0.684 ,  0.6296]])

In [25]:
names =='Bob'

array([ True, False, False,  True, False, False, False])

In [26]:
data[names=='Bob']

array([[ 1.0506,  0.9001, -0.7518,  0.7778],
       [ 1.1021,  0.5007,  0.7032, -1.002 ]])

In [27]:
data[names=='Bob',2:]

array([[-0.7518,  0.7778],
       [ 0.7032, -1.002 ]])

In [28]:
data[names == 'Bob', 3]

array([ 0.7778, -1.002 ])

In [29]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [30]:
# data[-(names == 'Bob')]
data[~(names == 'Bob')]

array([[-0.5619,  0.2016, -0.7449, -0.0038],
       [ 1.5603,  0.4021,  0.82  ,  0.6513],
       [-0.1882,  0.7621,  0.1871, -0.1801],
       [-0.0625,  0.2762, -0.4286, -0.7441],
       [-2.3445,  0.6991,  0.684 ,  0.6296]])

In [31]:
data[ (names != 'Bob')]

array([[-0.5619,  0.2016, -0.7449, -0.0038],
       [ 1.5603,  0.4021,  0.82  ,  0.6513],
       [-0.1882,  0.7621,  0.1871, -0.1801],
       [-0.0625,  0.2762, -0.4286, -0.7441],
       [-2.3445,  0.6991,  0.684 ,  0.6296]])

In [32]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [33]:
data[mask]

array([[ 1.0506,  0.9001, -0.7518,  0.7778],
       [ 1.5603,  0.4021,  0.82  ,  0.6513],
       [ 1.1021,  0.5007,  0.7032, -1.002 ],
       [-0.1882,  0.7621,  0.1871, -0.1801]])

In [35]:
data[data<0] = 0
data

array([[1.0506, 0.9001, 0.    , 0.7778],
       [0.    , 0.2016, 0.    , 0.    ],
       [1.5603, 0.4021, 0.82  , 0.6513],
       [1.1021, 0.5007, 0.7032, 0.    ],
       [0.    , 0.7621, 0.1871, 0.    ],
       [0.    , 0.2762, 0.    , 0.    ],
       [0.    , 0.6991, 0.684 , 0.6296]])

In [36]:
data[names != 'Joe'] = 7
data

array([[7.    , 7.    , 7.    , 7.    ],
       [0.    , 0.2016, 0.    , 0.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [0.    , 0.2762, 0.    , 0.    ],
       [0.    , 0.6991, 0.684 , 0.6296]])

In [38]:
arr = np.empty((8,4))
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [40]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [45]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [48]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [49]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [55]:
arr = np.arange(24).reshape((2,3,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [56]:
arr.transpose(2,1,0)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [57]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [59]:
arr.swapaxes(2,0)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])