In [1]:
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

In [3]:
x = randn(8)
x

array([-0.324 , -2.139 ,  0.4801,  0.4758, -0.1183,  0.4384, -0.1534,
       -1.0315])

In [6]:
arr = randn(7)*5
arr

array([-1.6904,  6.5395,  5.4976,  3.6045, -4.5233,  7.0418,  5.4608])

In [7]:
np.modf(arr)

(array([-0.6904,  0.5395,  0.4976,  0.6045, -0.5233,  0.0418,  0.4608]),
 array([-1.,  6.,  5.,  3., -4.,  7.,  5.]))

In [8]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [9]:
result = [(x if c else y )
          for x,y,c in zip(xarr,yarr,cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [10]:
result = np.where(cond,xarr,yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [12]:
arr = randn(4,4)
arr

array([[ 0.3842,  0.1105, -0.8371, -0.6461],
       [ 0.1207, -1.2542, -1.13  , -0.2238],
       [-1.4442, -1.7608,  0.7487, -0.3605],
       [ 0.9488, -0.8965,  0.0056, -1.2215]])

In [13]:
np.where(arr>0,2,-2)

array([[ 2,  2, -2, -2],
       [ 2, -2, -2, -2],
       [-2, -2,  2, -2],
       [ 2, -2,  2, -2]])

In [16]:
arr = randn(5,4)
arr

array([[ 0.0593,  0.2589, -0.017 ,  1.0334],
       [ 0.6686, -1.2515, -0.5145, -0.2176],
       [-1.5052, -1.4503,  0.8723,  0.4239],
       [ 0.4837, -1.2229,  0.0583,  1.0078],
       [-0.3601, -0.7341,  0.3201,  0.6507]])

In [17]:
arr.mean()

-0.07180433468756353

In [18]:
np.mean(arr)

-0.07180433468756353