In [1]:
import numpy as np

In [2]:
a = np.arange(12)**2

In [3]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [4]:
i = np.array([1,1,3,8,5])
i

array([1, 1, 3, 8, 5])

In [5]:
a[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [8]:
a = np.arange(15).reshape(3,5) 
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
a.shape

(3, 5)

In [10]:
a.ndim

2

In [11]:
a.itemsize

4

In [12]:
a.size

15

In [14]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [16]:
from numpy import pi

In [19]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])