In [1]:
# NumPy Basics
from IPython.display import Image 

In [2]:
from numpy.random import randn
import numpy as np


In [3]:
from os.path import exists
from os import remove

In [4]:
def delete_file(filename):
    if exists(filename): 
        remove(filename) 
        ret_msg = filename + ' is deleted !'
    else: 
        ret_msg = filename + ' is not exist.'
    
    return ret_msg

In [5]:
delete_file('some_array.npy')

'some_array.npy is not exist.'

In [6]:
delete_file('array_archive.npz')

'array_archive.npz is not exist.'

In [7]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.save('some_array', arr)

In [27]:
!dir *.np*

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 78D5-6279

 C:\Users\student\Anaconda_src\S01_Pyton_Review 디렉터리

2022-05-27  오전 09:20               930 array_archive.npz
2022-05-27  오전 09:17               168 some_array.npy
               2개 파일               1,098 바이트
               0개 디렉터리  206,269,853,696 바이트 남음


In [9]:
%ls *.np*

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 78D5-6279

 C:\Users\student\Anaconda_src\S01_Pyton_Review 디렉터리

2022-05-27  오전 09:17               168 some_array.npy
               1개 파일                 168 바이트
               0개 디렉터리  206,270,164,992 바이트 남음


In [25]:
%pwd

'C:\\Users\\student\\Anaconda_src\\S01_Pyton_Review'

In [10]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr2 = np.arange(100)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
np.savez('array_archive.npz', a = arr, b = arr2)

In [13]:
%ls *.np*

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 78D5-6279

 C:\Users\student\Anaconda_src\S01_Pyton_Review 디렉터리

2022-05-27  오전 09:18               570 array_archive.npz
2022-05-27  오전 09:17               168 some_array.npy
               2개 파일                 738 바이트
               0개 디렉터리  206,270,054,400 바이트 남음


In [23]:
arch = np.load('array_archive.npz')
print(type(arch))
arch['a']

<class 'numpy.lib.npyio.NpzFile'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
help(np.load)

Help on function load in module numpy:

load(file, mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII')
    Load arrays or pickled objects from ``.npy``, ``.npz`` or pickled files.
    
    .. warning:: Loading files that contain object arrays uses the ``pickle``
                 module, which is not secure against erroneous or maliciously
                 constructed data. Consider passing ``allow_pickle=False`` to
                 load data that is known not to contain object arrays for the
                 safer handling of untrusted sources.
    
    Parameters
    ----------
    file : file-like object, string, or pathlib.Path
        The file to read. File-like objects must support the
        ``seek()`` and ``read()`` methods. Pickled files require that the
        file-like object support the ``readline()`` method as well.
    mmap_mode : {None, 'r+', 'r', 'w+', 'c'}, optional
        If not None, then memory-map the file, using the given mode (see
        `n

In [37]:
!mkdir data

In [38]:
filename = 'data/array_ex.csv'

*미리 확인하고 들어간다

In [42]:
delete_file(filename)

'data/array_ex.csv is deleted !'

In [43]:
data = '''\
 0.580052,  0.186730,  1.040717,  1.134411
 0.194163, -0.636917, -0.938659,  0.124094
-0.126410,  0.268607, -0.695724,  0.047428
-1.484413,  0.004176, -0.744203,  0.005487
 2.302869,  0.200131,  1.670238, -1.881090
-0.193230,  1.047233,  0.482803,  0.960334\
'''
with open(filename, 'w') as fp:
    fp.write(data)
    
with open(filename, 'w') as fp:
    fp.write(data)

In [44]:
with open(filename, 'r') as fp:    
    data = fp.read()
    
with open(filename, 'r') as fp:
    data = fp.read()
    
print(data)


 0.580052,  0.186730,  1.040717,  1.134411
 0.194163, -0.636917, -0.938659,  0.124094
-0.126410,  0.268607, -0.695724,  0.047428
-1.484413,  0.004176, -0.744203,  0.005487
 2.302869,  0.200131,  1.670238, -1.881090
-0.193230,  1.047233,  0.482803,  0.960334


*array로 불러올 수 있는 방법

In [45]:
arr = np.loadtxt(filename, delimiter=',')
arr = np.loadtxt(filename, delimiter=',')

array([[ 0.580052,  0.18673 ,  1.040717,  1.134411],
       [ 0.194163, -0.636917, -0.938659,  0.124094],
       [-0.12641 ,  0.268607, -0.695724,  0.047428],
       [-1.484413,  0.004176, -0.744203,  0.005487],
       [ 2.302869,  0.200131,  1.670238, -1.88109 ],
       [-0.19323 ,  1.047233,  0.482803,  0.960334]])

In [46]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [48]:
x.dot(y)  # equivalently np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [51]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [52]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [54]:
x@y

array([[ 28.,  64.],
       [ 67., 181.]])

In [61]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [108]:
np.dot(y, np.ones(2))

array([29.,  6., 17.])

In [109]:
np.ones(2)

array([1., 1.])

In [56]:
? np.ones

In [107]:
np.random.seed(1)
arr = np.random.randint(99,size = 6)
arr

array([37, 12, 72,  9, 75,  5])

In [79]:
from random import normalvariate
N = 1000000

In [71]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

663 ms ± 2.86 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [72]:
%timeit np.random.normal(size = N)

22.3 ms ± 31.9 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
