In [1]:
# from images import bigpycraft_bda as bpc
from IPython.display import Image 

import numpy as np
import pandas as pd
# import canvas as plt
import matplotlib.pyplot as plt

In [ ]:
ex1 = pd.read_excel('./data/2014_d.xlsx')
ex2 = pd.read_excel('./data/2015_d.xlsx')
ex3 = pd.read_excel('./data/2016_d.xlsx')
ex1
ex2
ex3

In [ ]:
data = pd.concat([ex1,ex2,ex3])
data.set_index('구분',inplace=True)
data


In [ ]:
ans2 = data.copy()
ans2.index = pd.to_datetime(ans2.index, format='%Y년%m월')
ans2.set_index([ans2.index.year,ans2.index.month], inplace=True)
ans2.index.names = ['년도','월']
ans2

In [ ]:
y = ans2.groupby('년도').mean()[['사망(명)']]
m = ans2.groupby('월').mean()[['사망(명)']]
round(y,0), round(m,0)

In [ ]:
y2 = ans2.groupby('년도').mean()[['부상(명)']]
m2 = ans2.groupby('월').mean()[['부상(명)']]
round(y2,0),round(m2,0)

In [ ]:
d_2016 = ( ans2.loc[2016])['사망(명)'].sum()/( ans2.loc[2016])['사고(건)'].sum()
d_2016

In [ ]:
d_2016 = ( ans2.loc[2016])['부상(명)'].sum()/( ans2.loc[2016])['사고(건)'].sum()
d_2016

In [ ]:
# %pip install matplotlib

In [ ]:
?plt.plot

In [ ]:
ans2.loc[2014][['사망(명)','부상(명)']].plot(kind='bar',rot=0)
plt.show()

In [ ]:
ans2.loc[2015][['사망(명)','부상(명)']].plot(kind='bar',rot=0)
plt.show()

In [ ]:
data

In [ ]:
(ans2.loc[2016,'사망(명)'] - ans2.loc[2015,'사망(명)']).nlargest(4,keep='all')

In [ ]:
ser1 = pd.Series(list(['abcedfghijklmnopqrstuvwxyz']))
ser1

In [ ]:
ser2 = pd.Series(np.arange(26))
ser2

In [ ]:
df = pd.DataFrame({'col1': ser1, 'col2': ser2})
print(df.head())

In [ ]:
df = pd.concat([ser1,ser2],axis=1)
df

In [ ]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

In [ ]:
ser.name = 'alphabets'
ser.head()

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])

In [ ]:
ser2 = pd.Series([4, 5, 6, 7, 8])

In [ ]:
ser1[~ser1.isin(ser2)]

In [ ]:
ser1[ser1.isin(ser2)]

In [ ]:
ser = pd.Series(np.random.normal(10, 5, 25))
ser

In [ ]:
np.percentile(ser, q=[0, 25, 50, 75, 100])

In [ ]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser

In [ ]:
ser.value_counts()

In [ ]:
np.random.RandomState(100)

In [ ]:
ser = pd.Series(np.random.randint(1, 5, [12]))
ser

In [ ]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
ser

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 7))
ser

In [6]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
ser

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [7]:
pos = [0, 4, 8, 14, 20]
pos

[0, 4, 8, 14, 20]

In [8]:
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [ ]:
np.argwhere(ser % 3==0)

In [11]:
ser1 = pd.Series(range(5))
ser1

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [12]:
ser2 = pd.Series(list('abcde'))
ser2

0    a
1    b
2    c
3    d
4    e
dtype: object

In [13]:
ser1.append(ser2)

C:\Users\student\AppData\Local\Temp\ipykernel_7484\739202500.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ser1.append(ser2)


0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

In [14]:
df = pd.concat([ser1, ser2], axis=1)
print(df)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [15]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])

In [17]:
ser2 = pd.Series([1, 3, 10, 13])

In [18]:
[np.where(i == ser1)[0].tolist()[0] for i in ser2]

[5, 4, 0, 8]

In [19]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [20]:
ser.map(lambda x: x.title())

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [21]:
pd.Series([i.title() for i in ser])

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [ ]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [22]:
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

In [23]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [26]:
print(ser.diff())

0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    6.0
7    8.0
dtype: float64


In [24]:
print(ser.diff().tolist()) #리스트화

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]


In [25]:
print(ser.diff().diff().tolist())

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


In [27]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [28]:
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [29]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

In [30]:
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

In [31]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

In [33]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weight = pd.Series(np.linspace(1, 10, 10))
print(weight.tolist())
print(fruit.tolist())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'banana', 'apple', 'apple', 'carrot', 'apple', 'carrot', 'apple', 'apple', 'apple']


In [34]:
weight.groupby(fruit).mean()

apple     6.666667
banana    1.500000
carrot    6.000000
dtype: float64

In [36]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[arr %2 == 1]

array([1, 3, 5, 7, 9])

In [38]:
arr[arr %2 == 1]=-1

In [39]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [47]:
?np.reshape

In [50]:
a = np.arange(10).reshape(2,-1)
a
b = np.repeat(1,10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [51]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [52]:
np.concatenate([a,b],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [53]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [54]:
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [56]:
a = np.array([1,2,3])

In [59]:
np.vstack([np.repeat(a, 3), np.tile(a, 3)])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [60]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [61]:
np.intersect1d(a,b)

array([2, 4])

In [62]:
np.setdiff1d(a,b)

array([1, 3, 5, 6])