In [1]:
from tqdm import tqdm_notebook

In [2]:
# 머신러닝으로 업종별 매출액 예상하기?

# import tensorflow as tf
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

tf.set_random_seed(777)  # for reproducibility

# Training Data 2dim: x1(hours), x2(attendence)
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]  
# Result Data : y(0:fail or 1:pass)
y_data = [[0], [0], [0], [1], [1], [1]]                     

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b) # 아까 그 그래프가 sigmoid 이다.

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in tqdm_notebook(range(10001)):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0 or step < 10 :
            print("Step : {} \t Cost : {}".format(step, cost_val))
            
    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})

C:\Users\student\AppData\Local\Temp\ipykernel_2784\367348450.py:6: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for step in tqdm_notebook(range(10001)):


  0%|          | 0/10001 [00:00<?, ?it/s]

Step : 0 	 Cost : 0.7430492043495178
Step : 1 	 Cost : 0.7321328520774841
Step : 2 	 Cost : 0.72150057554245
Step : 3 	 Cost : 0.7111538052558899
Step : 4 	 Cost : 0.7010929584503174
Step : 5 	 Cost : 0.6913184523582458
Step : 6 	 Cost : 0.6818299889564514
Step : 7 	 Cost : 0.6726274490356445
Step : 8 	 Cost : 0.6637097001075745
Step : 9 	 Cost : 0.6550756096839905
Step : 200 	 Cost : 0.4218468964099884
Step : 400 	 Cost : 0.3823147714138031
Step : 600 	 Cost : 0.3591019809246063
Step : 800 	 Cost : 0.3428586423397064
Step : 1000 	 Cost : 0.33000972867012024
Step : 1200 	 Cost : 0.31902754306793213
Step : 1400 	 Cost : 0.3091982305049896
Step : 1600 	 Cost : 0.3001621663570404
Step : 1800 	 Cost : 0.29172614216804504
Step : 2000 	 Cost : 0.28377869725227356
Step : 2200 	 Cost : 0.2762506902217865
Step : 2400 	 Cost : 0.26909589767456055
Step : 2600 	 Cost : 0.26228079199790955
Step : 2800 	 Cost : 0.25577929615974426
Step : 3000 	 Cost : 0.24956989288330078
Step : 3200 	 Cost : 0.24363

In [4]:
print("# Hypothesis: \n{h} \n\n# Correct (Y): \n{c} \n\n# Accuracy: {a}".format(
    h = h, c = c, a = a
))

# Hypothesis: 
[[0.0242024 ]
 [0.1489122 ]
 [0.27185953]
 [0.79689527]
 [0.9489273 ]
 [0.9833507 ]] 

# Correct (Y): 
[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 

# Accuracy: 1.0


In [16]:
# Ask score many
print("\nOther scores \t: \n", sess.run(hypothesis,
                                        feed_dict={X : [10, 1]}))

RuntimeError: Attempted to use a closed Session.

In [6]:
import pandas as pd

# df = pd.read_csv("./data/data-03-diabetes.csv")
df = pd.read_csv("./data/data-03-diabetes.csv", header=None)
df.head(10)

0         1         2         3         4         5         6  \
0 -0.294118  0.487437  0.180328 -0.292929  0.000000  0.001490 -0.531170   
1 -0.882353 -0.145729  0.081967 -0.414141  0.000000 -0.207153 -0.766866   
2 -0.058824  0.839196  0.049180  0.000000  0.000000 -0.305514 -0.492741   
3 -0.882353 -0.105528  0.081967 -0.535354 -0.777778 -0.162444 -0.923997   
4  0.000000  0.376884 -0.344262 -0.292929 -0.602837  0.284650  0.887276   
5 -0.411765  0.165829  0.213115  0.000000  0.000000 -0.236960 -0.894962   
6 -0.647059 -0.216080 -0.180328 -0.353535 -0.791962 -0.076006 -0.854825   
7  0.176471  0.155779  0.000000  0.000000  0.000000  0.052161 -0.952178   
8 -0.764706  0.979899  0.147541 -0.090909  0.283688 -0.090909 -0.931682   
9 -0.058824  0.256281  0.573770  0.000000  0.000000  0.000000 -0.868488   

          7  8  
0 -0.033333  0  
1 -0.666667  1  
2 -0.633333  0  
3  0.000000  1  
4 -0.600000  0  
5 -0.700000  1  
6 -0.833333  0  
7 -0.733333  1  
8  0.066667  0  
9  0.100000  0

In [8]:
# Lab 5 Logistic Regression Classifier
# import tensorflow as tf
import tensorflow.compat.v1 as tf
import numpy as np

tf.disable_v2_behavior()

tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('./data/data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# print(x_data.shape, y_data.shape)
print(" x_data.shape : {x_shape} \n y_data.shape : {y_shape}".format(
        x_shape = x_data.shape, 
        y_shape = y_data.shape
    ))

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b) # 1,0으값 -> sigmoid

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

 x_data.shape : (759, 8) 
 y_data.shape : (759, 1)


In [9]:
print(len(xy)) 
xy[:10]

759


array([[-0.294118  ,  0.487437  ,  0.180328  , -0.292929  ,  0.        ,
         0.00149028, -0.53117   , -0.0333333 ,  0.        ],
       [-0.882353  , -0.145729  ,  0.0819672 , -0.414141  ,  0.        ,
        -0.207153  , -0.766866  , -0.666667  ,  1.        ],
       [-0.0588235 ,  0.839196  ,  0.0491803 ,  0.        ,  0.        ,
        -0.305514  , -0.492741  , -0.633333  ,  0.        ],
       [-0.882353  , -0.105528  ,  0.0819672 , -0.535354  , -0.777778  ,
        -0.162444  , -0.923997  ,  0.        ,  1.        ],
       [ 0.        ,  0.376884  , -0.344262  , -0.292929  , -0.602837  ,
         0.28465   ,  0.887276  , -0.6       ,  0.        ],
       [-0.411765  ,  0.165829  ,  0.213115  ,  0.        ,  0.        ,
        -0.23696   , -0.894962  , -0.7       ,  1.        ],
       [-0.647059  , -0.21608   , -0.180328  , -0.353535  , -0.791962  ,
        -0.0760059 , -0.854825  , -0.833333  ,  0.        ],
       [ 0.176471  ,  0.155779  ,  0.        ,  0.        ,  0

In [10]:
print(len(x_data)) 
x_data[:10]

759


array([[-0.294118  ,  0.487437  ,  0.180328  , -0.292929  ,  0.        ,
         0.00149028, -0.53117   , -0.0333333 ],
       [-0.882353  , -0.145729  ,  0.0819672 , -0.414141  ,  0.        ,
        -0.207153  , -0.766866  , -0.666667  ],
       [-0.0588235 ,  0.839196  ,  0.0491803 ,  0.        ,  0.        ,
        -0.305514  , -0.492741  , -0.633333  ],
       [-0.882353  , -0.105528  ,  0.0819672 , -0.535354  , -0.777778  ,
        -0.162444  , -0.923997  ,  0.        ],
       [ 0.        ,  0.376884  , -0.344262  , -0.292929  , -0.602837  ,
         0.28465   ,  0.887276  , -0.6       ],
       [-0.411765  ,  0.165829  ,  0.213115  ,  0.        ,  0.        ,
        -0.23696   , -0.894962  , -0.7       ],
       [-0.647059  , -0.21608   , -0.180328  , -0.353535  , -0.791962  ,
        -0.0760059 , -0.854825  , -0.833333  ],
       [ 0.176471  ,  0.155779  ,  0.        ,  0.        ,  0.        ,
         0.052161  , -0.952178  , -0.733333  ],
       [-0.764706  ,  0.979899  

In [11]:
print(len(y_data)) 
y_data[:10]

759


array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.]], dtype=float32)

In [14]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in tqdm_notebook(range(20001)):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})       
        if step % 200 == 0 or step < 10 :
            print("Step : {} \t Cost : {}".format(step, cost_val))    

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})

C:\Users\student\AppData\Local\Temp\ipykernel_2784\1152247385.py:6: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for step in tqdm_notebook(range(20001)):


  0%|          | 0/20001 [00:00<?, ?it/s]

Step : 0 	 Cost : 1.0378105640411377
Step : 1 	 Cost : 1.0360039472579956
Step : 2 	 Cost : 1.0342001914978027
Step : 3 	 Cost : 1.0323994159698486
Step : 4 	 Cost : 1.0306012630462646
Step : 5 	 Cost : 1.028806209564209
Step : 6 	 Cost : 1.0270142555236816
Step : 7 	 Cost : 1.0252249240875244
Step : 8 	 Cost : 1.023438811302185
Step : 9 	 Cost : 1.0216553211212158
Step : 200 	 Cost : 0.7447590827941895
Step : 400 	 Cost : 0.600660502910614
Step : 600 	 Cost : 0.5523813962936401
Step : 800 	 Cost : 0.5376949906349182
Step : 1000 	 Cost : 0.5314603447914124
Step : 1200 	 Cost : 0.527259886264801
Step : 1400 	 Cost : 0.5237146019935608
Step : 1600 	 Cost : 0.5205262303352356
Step : 1800 	 Cost : 0.5176125764846802
Step : 2000 	 Cost : 0.5149363875389099
Step : 2200 	 Cost : 0.5124714374542236
Step : 2400 	 Cost : 0.5101962685585022
Step : 2600 	 Cost : 0.5080920457839966
Step : 2800 	 Cost : 0.5061423182487488
Step : 3000 	 Cost : 0.5043325424194336
Step : 3200 	 Cost : 0.50264972448349


In [15]:
print("# Hypothesis: \n{h} \n\n# Correct (Y): \n{c} \n\n# Accuracy: {a}".format(
    # h = h, c = c, a = a
    h = h[:20], c = c[:20], a = a
)) # 전문의가 진단했을때 75%로 이 모델은 거의 이렇게 나온다.

# Hypothesis: 
[[0.3568853 ]
 [0.94513816]
 [0.23751095]
 [0.9574887 ]
 [0.11800208]
 [0.8324478 ]
 [0.9549511 ]
 [0.5947919 ]
 [0.18776229]
 [0.5815853 ]
 [0.7338283 ]
 [0.12974496]
 [0.32954434]
 [0.15344585]
 [0.7983915 ]
 [0.4101635 ]
 [0.7948825 ]
 [0.8071473 ]
 [0.8221144 ]
 [0.58300954]] 

# Correct (Y): 
[[0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 

# Accuracy: 0.7707509994506836
