In [7]:
from numpy.random import randn
import numpy as np

In [29]:
np.random.seed(0)

In [30]:
nsteps = 1000
draws = np.random.randint(0, 2, size = nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [31]:
walk.min()

-5

In [32]:
walk.max()

36

In [33]:
draws

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,

In [34]:
steps

array([-1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1,  1, -1, -1, -1,
       -1, -1,  1, -1,  1,  1, -1, -1,  1,  1,  1,  1, -1,  1, -1,  1, -1,
        1,  1, -1,  1,  1, -1, -1,  1, -1,  1,  1,  1,  1,  1, -1,  1, -1,
        1,  1,  1,  1, -1,  1, -1, -1,  1,  1, -1,  1, -1,  1, -1, -1, -1,
       -1, -1,  1,  1, -1, -1, -1,  1,  1, -1,  1, -1, -1,  1, -1,  1,  1,
        1,  1,  1,  1, -1,  1,  1, -1, -1,  1, -1, -1,  1,  1, -1,  1, -1,
       -1,  1, -1, -1, -1,  1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1,  1,
       -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1,  1,
       -1, -1, -1, -1,  1,  1, -1, -1,  1, -1,  1,  1,  1,  1, -1, -1, -1,
        1, -1,  1,  1,  1, -1,  1, -1, -1,  1, -1,  1,  1, -1, -1,  1, -1,
        1, -1,  1, -1,  1, -1,  1, -1, -1, -1,  1, -1,  1, -1,  1, -1, -1,
       -1, -1, -1,  1, -1, -1,  1, -1, -1, -1,  1, -1, -1,  1, -1,  1, -1,
       -1,  1,  1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1,  1, -1,  1, -1,
       -1, -1,  1,  1,  1

In [35]:
walk

array([-1,  0,  1,  0,  1,  2,  3,  4,  5,  6,  7,  6,  5,  6,  5,  4,  3,
        2,  1,  2,  1,  2,  3,  2,  1,  2,  3,  4,  5,  4,  5,  4,  5,  4,
        5,  6,  5,  6,  7,  6,  5,  6,  5,  6,  7,  8,  9, 10,  9, 10,  9,
       10, 11, 12, 13, 12, 13, 12, 11, 12, 13, 12, 13, 12, 13, 12, 11, 10,
        9,  8,  9, 10,  9,  8,  7,  8,  9,  8,  9,  8,  7,  8,  7,  8,  9,
       10, 11, 12, 13, 12, 13, 14, 13, 12, 13, 12, 11, 12, 13, 12, 13, 12,
       11, 12, 11, 10,  9, 10, 11, 10, 11, 10,  9,  8,  7,  6,  7,  6,  7,
        6,  7,  8,  9, 10, 11, 10, 11, 12, 13, 14, 13, 14, 15, 14, 13, 14,
       13, 12, 11, 10, 11, 12, 11, 10, 11, 10, 11, 12, 13, 14, 13, 12, 11,
       12, 11, 12, 13, 14, 13, 14, 13, 12, 13, 12, 13, 14, 13, 12, 13, 12,
       13, 12, 13, 12, 13, 12, 13, 12, 11, 10, 11, 10, 11, 10, 11, 10,  9,
        8,  7,  6,  7,  6,  5,  6,  5,  4,  3,  4,  3,  2,  3,  2,  3,  2,
        1,  2,  3,  2,  1,  0,  1,  2,  1,  0, -1, -2, -3, -2, -3, -2, -3,
       -4, -5, -4, -3, -2

In [38]:
(np.abs(walk) >= 10)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,

In [39]:
(np.abs(walk) >= 10).argmax()

47

In [61]:
nwalks = 10
nsteps = 5
draws = np.random.randint(0, 2, size = (nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

array([[-1, -2, -1,  0, -1],
       [-1, -2, -3, -4, -5],
       [ 1,  0, -1, -2, -1],
       [ 1,  2,  3,  4,  5],
       [-1,  0, -1, -2, -1],
       [-1, -2, -3, -4, -3],
       [ 1,  2,  1,  2,  1],
       [-1, -2, -3, -4, -3],
       [-1, -2, -1,  0,  1],
       [ 1,  2,  1,  2,  1]], dtype=int32)

In [62]:
draws

array([[0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 1, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 1, 1],
       [1, 1, 0, 1, 0]])

In [63]:
steps

array([[-1, -1,  1,  1, -1],
       [-1, -1, -1, -1, -1],
       [ 1, -1, -1, -1,  1],
       [ 1,  1,  1,  1,  1],
       [-1,  1, -1, -1,  1],
       [-1, -1, -1, -1,  1],
       [ 1,  1, -1,  1, -1],
       [-1, -1, -1, -1,  1],
       [-1, -1,  1,  1,  1],
       [ 1,  1, -1,  1, -1]])

In [64]:
walks.min()

-5

In [65]:
walks.max()

5

In [66]:
(np.abs(walks) >= 5).argmax()

9

In [70]:
hits5 = (np.abs(walks) >= 5).any(1)
hits5

array([False,  True, False,  True, False, False, False, False, False,
       False])

In [71]:
hits5.sum()

2

In [73]:
crossing_times = (np.abs(walks[hits5]) >= 5).argmax(1)
crossing_times.mean()

4.0

In [77]:
?np.argmax

In [78]:
steps = np.random.normal(loc=0, scale=0.25,
                         size=(nwalks, nsteps))

In [79]:
steps

array([[ 0.20437992,  0.02307897, -0.18238106,  0.17758365,  0.07141747],
       [ 0.12667566,  0.15430062, -0.17245924,  0.68927027, -0.20072986],
       [-0.18160615, -0.29082503,  0.36041555, -0.21657708,  0.73816274],
       [-0.23756302, -0.05959835, -0.07252497, -0.10348805,  0.16120224],
       [-0.22371743, -0.05922896,  0.09120209, -0.11222148,  0.33403883],
       [ 0.33316319,  0.40922269,  0.38273163, -0.37016771,  0.02275939],
       [-0.41172524, -0.47717869,  0.30633245, -0.24689153,  0.14064361],
       [-0.42061397,  0.06711803,  0.19117857,  0.10563146,  0.2376414 ],
       [-0.35968937,  0.20491611, -0.00718257,  0.03770737, -0.00201864],
       [ 0.18171817, -0.23020034, -0.07054335,  0.00259929,  0.05230917]])